# setup-host.ps1 - One-click setup for new host (Windows)
#
# Purpose:
#   Link this repository's portable assets back to Claude Code's local directories:
#     1. memory/ -> junction to ~/.claude/projects/{project-name}/memory
#     2. skills/ -> junction to ~/.claude/skills
#   (.claude/agents/ is loaded directly from the repository, so no junction is required.)
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File <repo>\setting\setup-host.ps1
#
# Note:
#   Claude Code project name = repository absolute path with all [:\/] replaced by '-'.

$ErrorActionPreference = 'Stop'

$repo = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path.TrimEnd('\')
$projName = ($repo -replace '[:\\/]', '-')

$claudeDir = Join-Path $env:USERPROFILE '.claude'
$projDir   = Join-Path $claudeDir "projects\$projName"

New-Item -ItemType Directory -Force $projDir | Out-Null

function Connect-Link([string]$linkPath, [string]$target) {
    $target = $target.TrimEnd('\')

    if (Test-Path $linkPath) {
        $item = Get-Item $linkPath -Force

        if ($item.LinkType -eq 'Junction') {
            $currentTarget = (@($item.Target) | Select-Object -First 1).TrimEnd('\')

            if ($currentTarget -eq $target) {
                Write-Host "Already linked, skipping: $linkPath"
                return
            }

            Write-Host "Junction target is stale ($currentTarget -> $target expected). Relinking: $linkPath"
            Remove-Item $linkPath -Force
        } else {
            $bak = "$linkPath.pre-link.bak"
            Write-Host "Existing path detected. Moving it to $bak"
            Move-Item $linkPath $bak
        }
    }

    New-Item -ItemType Junction -Path $linkPath -Target $target | Out-Null
    Write-Host "Linked: $linkPath -> $target"
}

Connect-Link (Join-Path $projDir 'memory') (Join-Path $repo 'memory')
Connect-Link (Join-Path $claudeDir 'skills') (Join-Path $repo 'skills')

# reference_knowledge_base.md is git-tracked and portable across hosts, so it cannot
# contain this host's real absolute KB path. Instead, write that path into a
# gitignored, host-local sibling file that reference_knowledge_base.md points to.
$localRefPath = Join-Path $repo 'memory\reference_knowledge_base.local.md'
$localRefContent = @"
---
name: reference-knowledge-base-local
description: Actual local Knowledge Hub path (auto-generated by setup-host.ps1, not tracked in git, host-specific)
metadata:
  node_type: memory
  type: reference
---

Local Knowledge Hub root path: ``$repo``
"@
Set-Content -Path $localRefPath -Value $localRefContent -Encoding utf8
Write-Host "Wrote host-local KB path: $localRefPath"

# setting/paths.yml is git-tracked and intentionally has no `kb:` root path
# key - all consumers (CLAUDE.md, skills/quiz, skills/update-kb, sdlc-agent)
# resolve $KB_ROOT from the memory file written above, never from paths.yml.
# This script does not touch paths.yml.

# Global, non-project-scoped anchor so other tooling (e.g. the SessionStart
# auto-link hook, setting/check-memory-link.ps1) can find the KB root from any
# working directory without depending on any single project's junction.
$kbRootAnchor = Join-Path $claudeDir 'kb-root.txt'
Set-Content -Path $kbRootAnchor -Value $repo -Encoding utf8 -NoNewline
Write-Host "Wrote global KB root anchor: $kbRootAnchor"

# Register the SessionStart hooks (user-level settings.json, so they fire no
# matter which directory `claude` is launched from). Idempotent: merges with
# existing settings, skips any hook that's already registered.
function Register-SessionStartHook([object]$settings, [string]$hookScriptPath) {
    $hookCommand = "powershell -NoProfile -ExecutionPolicy Bypass -File `"$hookScriptPath`""
    $scriptName = Split-Path $hookScriptPath -Leaf

    foreach ($entry in @($settings.hooks.SessionStart)) {
        foreach ($h in @($entry.hooks)) {
            if ($h.command -like "*$scriptName*") {
                Write-Host "SessionStart hook already registered, skipping: $scriptName"
                return $false
            }
        }
    }

    $newEntry = [PSCustomObject]@{
        hooks = @(, [PSCustomObject]@{ type = 'command'; command = $hookCommand; timeout = 15 })
    }
    $settings.hooks.SessionStart = @(, @(@($settings.hooks.SessionStart) + $newEntry))[0]
    Write-Host "Registered SessionStart hook: $scriptName"
    return $true
}

$settingsPath = Join-Path $claudeDir 'settings.json'

if (Test-Path $settingsPath) {
    $settings = Get-Content $settingsPath -Raw -Encoding UTF8 | ConvertFrom-Json
} else {
    $settings = [PSCustomObject]@{}
}
if (-not ($settings.PSObject.Properties.Name -contains 'hooks')) {
    $settings | Add-Member -NotePropertyName 'hooks' -NotePropertyValue ([PSCustomObject]@{})
}
if (-not ($settings.hooks.PSObject.Properties.Name -contains 'SessionStart')) {
    $settings.hooks | Add-Member -NotePropertyName 'SessionStart' -NotePropertyValue @()
}

$memoryLinkAdded  = Register-SessionStartHook $settings (Join-Path $repo 'setting\check-memory-link.ps1')
$projectKbAdded   = Register-SessionStartHook $settings (Join-Path $repo 'setting\check-project-kb.ps1')
$checkSkillsAdded = Register-SessionStartHook $settings (Join-Path $repo 'setting\check-skills.ps1')

if ($memoryLinkAdded -or $projectKbAdded -or $checkSkillsAdded) {
    ($settings | ConvertTo-Json -Depth 10) | Set-Content -Path $settingsPath -Encoding UTF8
    Write-Host "Updated $settingsPath"
}

Write-Host ""
Write-Host "Setup completed."
Write-Host "Project name: $projName"
Write-Host "Please open Claude Code in the repository and verify that both memory and skills are available."

