#!/usr/bin/env bash
# setup-host.sh - One-click setup for a new host (macOS / Linux)
#
# Purpose:
#   Link this repository's portable assets back to Claude Code's local directories:
#     - memory/ -> ~/.claude/projects/{project-name}/memory
#     - skills/ -> ~/.claude/skills
#
# Usage:
#   bash <repo>/setting/setup-host.sh
#
# Note:
#   Claude Code project name = repository absolute path with all [:/] replaced by '-'
#   Example:
#     /home/rita/engineering-hub
#       ->
#     -home-rita-engineering-hub

set -euo pipefail

repo="$(cd "$(dirname "$0")/.." && pwd)"
proj_name="$(printf '%s' "$repo" | sed 's|[:/]|-|g')"

claude_dir="$HOME/.claude"
proj_dir="$claude_dir/projects/$proj_name"

mkdir -p "$proj_dir"

link() {
    local link_path="$1"
    local target="$2"

    if [ -L "$link_path" ]; then
        echo "Already linked, skipping: $link_path"
        return
    fi

    if [ -e "$link_path" ]; then
        mv "$link_path" "$link_path.pre-link.bak"
        echo "Existing path detected. Moved to ${link_path}.pre-link.bak"
    fi

    ln -s "$target" "$link_path"
    echo "Linked: $link_path -> $target"
}

link "$proj_dir/memory" "$repo/memory"
link "$claude_dir/skills" "$repo/skills"

# reference_knowledge_base.md is git-tracked and portable across hosts, so it cannot
# contain this host's real absolute KB path. Instead, write that path into a
# gitignored, host-local sibling file that reference_knowledge_base.md points to.
local_ref_path="$repo/memory/reference_knowledge_base.local.md"
cat > "$local_ref_path" <<EOF
---
name: reference-knowledge-base-local
description: Actual local Knowledge Hub path (auto-generated by setup-host.sh, not tracked in git, host-specific)
metadata:
  node_type: memory
  type: reference
---

Local Knowledge Hub root path: \`$repo\`
EOF
echo "Wrote host-local KB path: $local_ref_path"

# Keep setting/paths.yml's `kb:` line in sync with the same $repo value.
# This file IS git-tracked (unlike reference_knowledge_base.local.md above),
# because two consumers (skills/quiz, this repo's own root CLAUDE.md) read
# `kb:` directly without going through memory. Writing it from the same
# $repo variable as the local-only memory file keeps both sources from
# drifting apart; re-running this script on a different host simply
# re-resolves it to that host's path.
# (Written via a temp file + mv rather than `sed -i` so this works identically
# on both GNU sed (Linux) and BSD sed (macOS), whose -i flags are incompatible.)
paths_yml_path="$repo/setting/paths.yml"
sed "s|^kb:[[:space:]]*'.*'|kb: '$repo'|" "$paths_yml_path" > "$paths_yml_path.tmp"
mv "$paths_yml_path.tmp" "$paths_yml_path"
echo "Synced setting/paths.yml kb: -> $repo"

# Global, non-project-scoped anchor so other tooling (e.g. the SessionStart
# auto-link hooks, setting/check-memory-link.sh and setting/check-project-kb.sh)
# can find the KB root from any working directory without depending on any
# single project's junction.
kb_root_anchor="$claude_dir/kb-root.txt"
printf '%s' "$repo" > "$kb_root_anchor"
echo "Wrote global KB root anchor: $kb_root_anchor"

# Register the SessionStart hooks (user-level settings.json, so they fire no
# matter which directory `claude` is launched from). Idempotent: merges with
# existing settings, skips any hook that's already registered. Requires jq,
# since hand-rolled JSON editing in shell is too fragile for a file that also
# holds unrelated user settings.
settings_path="$claude_dir/settings.json"
chmod +x "$repo/setting/check-memory-link.sh" "$repo/setting/check-project-kb.sh" "$repo/setting/check-skills.sh" 2>/dev/null || true

if ! command -v jq >/dev/null 2>&1; then
    echo "jq not found - skipping SessionStart hook registration."
    echo "Install jq (e.g. 'brew install jq' or 'apt install jq') and re-run this script to register the hooks."
else
    if [ ! -f "$settings_path" ]; then
        echo '{}' > "$settings_path"
    fi

    register_hook() {
        local script_path="$1"
        local script_name
        script_name="$(basename "$script_path")"
        local command="bash \"$script_path\""

        local already
        already="$(jq -r '(.hooks.SessionStart // [])[].hooks[]?.command // empty' "$settings_path" | grep -F "$script_name" || true)"

        if [ -n "$already" ]; then
            echo "SessionStart hook already registered, skipping: $script_name"
            return
        fi

        jq --arg cmd "$command" '
            .hooks = (.hooks // {})
            | .hooks.SessionStart = ((.hooks.SessionStart // []) + [{"hooks": [{"type": "command", "command": $cmd, "timeout": 15}]}])
        ' "$settings_path" > "$settings_path.tmp"
        mv "$settings_path.tmp" "$settings_path"
        echo "Registered SessionStart hook: $script_name"
    }

    register_hook "$repo/setting/check-memory-link.sh"
    register_hook "$repo/setting/check-project-kb.sh"
    register_hook "$repo/setting/check-skills.sh"
fi

echo ""
echo "Setup completed."
echo "Project name: $proj_name"
echo "Please open Claude Code in the repository and verify that both memory and skills are available."